module.exports = {
	assignment: require('./assignment.js'),
	squareBrackets: require('./square-brackets.js'),
	dot: require('./dot.js'),
	echo: require('./echo.js'),
	ignore: require('./ignore.js'),
	parenthesis: require('./parenthesis.js'),
	table: require('./table.js'),
	ifBranch: require('./if.js'),
	doubleEquals: require('./double-equals.js'),
	semicolon: require('./semicolon.js'),
	curlyBraces: require('./curly-braces.js'),
	simpleString: require('./simple-string.js'),
	macroArgument: require('./macro-argument.js'),
	plus: require('./plus.js'),
	booleanAnd: require('./boolean-and.js'),
	notEquals: require('./not-equals.js'),
	elseBranch: require('./else.js'),
	foreach: require('./foreach.js')
};